redis:
  ip: localhost
  port: 6379
  username: "none"
  password: "none"


servers:
  this-server: lobby
  main-server: true
  server-names:
    - survival
    - lobby

general:
  ticks-per-cycle: 3
  write-history: true
  delay-cycles: 2

integrations:
  elite-mobs: true
  aurelium-skills: true
  cmi: true
  jobs: true
  stats: true


