ip: localhost
port: 6379
interval: 3
username: "none"
password: "none"
load-data: true
write-history: true
server-names:
  - survival
  - lobby

server-name: lobby
main-server: true
elite-mobs: true
aurelium-skills: true
cmi: true
jobs: true

