name: DataSyncer
version: '${project.version}'
main: ru.mcfine.datasyncer.datasyncer.DataSyncer
softdepend: [EliteMobs, AureliumSkills, CMI]
api-version: 1.19
commands:
  datasync:
    description: Main command of the plugin.
    usage: Just use it.
